### ISSUE TITLE
Modals: should lock the body of the onwer document

### ISSUE THREAD

**Issue by Charca** [helpscout/blue#118]
## Problem

When opening a Modal, the `lockBody` method of the `PortalWrapper` HOC is called, which sets the `overflow` CSS prop of the body to `hidden`:

```javascript
document.body.style.overflow = 'hidden'
```

This works fine but when using a modal inside an iframe (like we do in the Beacon embed), it's the iframe's body that should get locked and not the host site's document.body. Possible to leverage the `getClosestDocument` util here?

**Comment by ItsJonQ** [comment]
@Charca Ohh! good idea :D.

(... 🤔 ...)

On second thought! This may not be necessary at all!

The new [ScrollLock](https://github.com/helpscout/blue/tree/master/src/components/ScrollLock) component built by @alisdair should be able to take care of this. `<ScrollLock>` was built into `<Scrollable>` a while back, which `<Modal>` uses to contain it's content.

Will test and make updates!

**Comment by ItsJonQ** [comment]
Confirmed. ScrollLock magically takes care of this. Will update the components to remove the old `body.style.overflow` "hack"
