### ISSUE TITLE
Icons for chat toolbar

### ISSUE THREAD

**Issue by tompedals** [helpscout/blue#129]
For the agent chat we need a couple of extra icons.

![screen shot 2017-11-29 at 19 55 48](https://user-images.githubusercontent.com/6132043/33396059-57139714-d53f-11e7-8ef0-d55c4962f14d.png)

* Avatar
* Tag

Also a way of adding a caret for dropdown icons would be really useful.

**Comment by ItsJonQ** [comment]
> Also a way of adding a caret for dropdown icons would be really useful.

Great idea!!

**Comment by ItsJonQ** [comment]
Just leaving notes. `<Icon>` can be enhanced with something like…

`<Icon name='tag' caret />`, where the `caret` prop (`bool`) will render a caret next to the icon.
