### ISSUE TITLE
Assigned user status dot

### ISSUE THREAD

**Issue by tompedals** [helpscout/blue#130]
For the agent chat toolbar we a status dot with a tick to represent the assigned user.

![screen shot 2017-11-29 at 19 59 08](https://user-images.githubusercontent.com/6132043/33396256-e1958500-d53f-11e7-9297-8c934cc0131a.png)

Perhaps this could be another state in the `StatusDot` component?

**Comment by ItsJonQ** [comment]
@tompedals Good idea!

Maybe a prop like `theme`. Default is `dot`, but can be changed to `icon` (for green check)
