### ISSUE TITLE
Bug: Scrollable component throwing TypeError

### ISSUE THREAD

**Issue by Charca** [helpscout/blue#146]
I've seen this happen in issue a few times, this started happening since I upgraded to 0.0.62 (I was in 58 before I believe). This doesn't happen all the time, and I can't reproduce 100%, but I've seen it happening when I open a modal and I close it quickly. Here's the error:

![Error](https://d1ax1i5f2y3x71.cloudfront.net/items/2Y1p3l390m0U1j331Z3D/Image%202017-12-04%20at%2011.38.34%20PM.png?X-CloudApp-Visitor-Id=3940ad2339d4442c5accc3972de29903&v=e3fdf3fa)

![Error2](https://d1ax1i5f2y3x71.cloudfront.net/items/3u393g1i021200431i34/Image%202017-12-04%20at%2011.41.46%20PM.png?X-CloudApp-Visitor-Id=3940ad2339d4442c5accc3972de29903&v=ac331456)

It looks like `this.faderNodeTop` is null for some reason when trying to change its `style` property.

**Comment by ItsJonQ** [comment]
@Charca Thanks!! Looking into this now

**Comment by ItsJonQ** [comment]
@Charca Created PR to fix it. It's weird as those nodes are set using `ref`, and theoretically should be set as soon as the component mounts. But… maybe there's a tiny window of time where it doesn't when you're mounting/unmount really fast?
