### ISSUE TITLE
Enhance `VisuallyHidden`'s `focusable` to allow for focus-scrolling

### ISSUE THREAD

**Issue by brettjonesdev** [helpscout/blue#170]
Sometimes, we need to force a scroll to a specific place on the page. The easiest way to do this is by focusing on an invisible link or input. 

The `VisuallyHidden` could be enhanced to make this easy to do: 
![image](https://user-images.githubusercontent.com/2163045/34225009-f6b13c52-e568-11e7-8c4d-73a2290c6d75.png)

The blockers right now are:
1. VisuallyHidden must be a Component class in order for `ref` to work
2. VisuallyHidden has a `position: absolute` that makes it not useful for this purpose 

Maybe we should create a separate component for sneaky focus-scrolls?

**Comment by ItsJonQ** [comment]
Closing this one! The interaction above was fixed using another solution 💪 !
