### ISSUE TITLE
Dropdown: Post-launch CANI/fixes

### ISSUE THREAD

**Issue by ItsJonQ** [helpscout/blue#65]
## Up next
* [x] Resolve `Drop` component handling of `onClose`/`onOpen` props
* [x] Should close entire dropdown, if nested dropdown item is clicked
* [ ] Improve `Positioner` handling of top/left top/right calculations
* [x] Add DropdownHeader
* [x] Add `disabled` state for DropdownItem
* [x] Update `Dropdown.Trigger` to render any item as a trigger
* [x] Consider Menu Header/Footer areas

## For later… (maybe much later)
* [ ] Add `Select` like abilities
* [ ] Add multi-select abilities

**Comment by ItsJonQ** [comment]
## Positioning coordinates

There **needs** to be more coordinates than just `up`, `left`, down`, `right`.

For example…

Below is an example of "up right":
```
|---------------|
| Content Block |
|---------------|
[ Trigger ]
```

Below is another example of "up right":

```
            |---------------|
            | Content Block |
[ Trigger ] |---------------|
```

Perhaps the order you describe the direction matters.

`up right` vs `right up`.

The first word is prioritized over the second.

This leads to the following possible directions:

`up`
`up left`
`up right`
`right`
`right up`
`right down`
`down`
`down left`
`down right`
`left`
`left up`
`left down`

The most interesting things are the singular descriptions, like `up` or `left`.

We can assume these mean `center`, which makes sense from a Popover/Tooltip perspective. So the list would actually be:

`up center`
`up left`
`up right`
`right center`
`right up`
`right down`
`down center`
`down left`
`down right`
`left center`
`left up`
`left down`

**Dropdown defaults**: `down right`
**Sub dropdown defaults**: `right down`
**Popover defaults**: `down center`
**Tooltip defaults**: `up center`

A possible mapping scheme can be…

`u1` | `u2` | `u3`

`u` being up, and 1/2/3 being left/center/right.

**Comment by knicklabs** [comment]
What are your plans for Dropdown header? 

I have a dropdown now that has a search input in the "header" area and a link in the "footer" area but this is accomplished simply by doing this (pseudocode to follow):

```
<Dropdown>
    <Dropdown.Trigger><a href="#">Toggle</a></Dropdown.Trigger>
    <Dropdown.Menu>
         <Search />
         <Dropdown.Divider />
         <Dropdown.Item>Item 1</Dropdown.Item>
         <Dropdown.Item>Item 2</Dropdown.Item>
         <Dropdown.Divider />
         <Link />
   </Dropdown.Menu>
</Dropdown>
```

This works because Dropdown.Menu takes any abitrary children. Between that and allowing custom classNames it makes for a very flexible component. 

One more issue I was running up against was the opinionated styling of the DropdrownTrigger. I believe this should add functionality to its child and render the child, instead of rendering a button with children. Again, this just makes things really flexible, so we could use a link, icon, image, or any arbitrary thing as a trigger to toggle the dropdown menu.

**Comment by knicklabs** [comment]
For example, the render method of Dropdown.Trigger could just render it's children like this:

```
  render() {
    return this.props.children
  }
```

I'm a fan of the idea of using any HTML element or other React component as a trigger.

**Comment by knicklabs** [comment]
One final consideration. I began looking at this Dropdown component with starry ideas with the idea of composing it with the InfiniteScroll component. Essentially, I wanted to a make a sub-menu with an infinite number of items.

**Comment by ItsJonQ** [comment]
@knicklabs All excellent suggestions!!!

I believe it's totally possible to use a non `<Dropdown.Trigger>` as a trigger at the moment. You just pass it as a child component instead of `<Dropdown.Trigger>`. However, I kind of like your idea better, as it makes it explicit!

I'll make that update!!
