### ISSUE TITLE
Only show title when dragging a SidebarCollapsibleCard element

### ISSUE THREAD

**Issue by lgariepy** [helpscout/blue#74]
In the spec for the Mailbox Sidebars, Buzz only wants to show the title of the SidebarCollapsibleCard element while it's being dragged:

![image_preview](https://user-images.githubusercontent.com/5752727/31519767-46aac7e2-af58-11e7-969f-0f3cb7ad9aee.png)

A gif of the idea in action:

![image_preview](https://user-images.githubusercontent.com/5752727/31519784-5f19fd8e-af58-11e7-80bb-f6cdc6d4073e.gif)

And then after the element is dropped, the card expands again.

Thanks for your help with this! Let me know if you have any questions.

**Comment by ItsJonQ** [comment]
Thanks Lauren! Just adding a linky to this issue for reference

Related: https://github.com/helpscout/blue/issues/71
