### ISSUE TITLE
Modal Component not closing on ESC KeyPress when running inside an iframe

### ISSUE THREAD

**Issue by Charca** [helpscout/blue#94]
The Modal component in Beacon is not closing on ESC KeyPress. We think this is because Beacon renders inside an iframe and the event is listening on the main document.body.

To reproduce, fire up [beacon2](https://github.com/helpscout/beacon2) locally, open any Docs article and hit the ESC key.

**Comment by ItsJonQ** [comment]
Investigated! Looks like events are being bound to the parent `window` / `document`, when we need them within the iFrame.

Will see how I can enhance `EventListener` / `KeypressListener` components to ✨ magically ✨ figure this out!

**Comment by ItsJonQ** [comment]
Update: 

In order for `EventListener`/`KeypressListener`… or any `window`/`document` based listener to **reliably** get the immediate parent document/window (which is needed for iFrame usage), I might need to add a helper function.

**Comment by ItsJonQ** [comment]
Resolved!
